repos:
  # Note for all linters: do not forget to update pyproject.toml when updating version.
  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        types: [python]
        # args: [--strict]
        additional_dependencies: 
          - sqlalchemy==2.0.23
          - pydantic==2.6.1
          - types-requests==2.31.0.20240125